/* file struct.h */

#define CAMERA_STRUCT        0
#define HOUSE_STRUCT         1  /* we lost it */
#define STREET_STRUCT        2  /* JUST DIED */
#define NEIGHBORHOOD_STRUCT  3  /*It killed itself */
#define FAKE_HOUSE_STRUCT    4
#define FAKE_NEIGHBORHOOD_TOP_STRUCT    5
#define FAKE_NEIGHBORHOOD_SIDE_STRUCT   6
#define GRID_STRUCT     7
#define TEXT_STRUCT		8
#define FAKE_HOUSE_TOP_STRUCT   9
#define FAKE_HOUSE_SIDE_STRUCT 10
#define AXES_STRUCT            11
#define CHIMNEY_STRUCT         12 /* JUST DIED */

/* Ours definitions - WE CANNOT DEFINE MORE THAN 15 ELEMENTS !!! */
#define  ROBOT_STRUCT       12
#define  FINGER_STRUCT      13
#define  LEFT_ARM_STRUCT    14
#define ALL_LEFT_ARM_STRUCT  3
#define ALL_RIGHT_ARM_STRUCT 1
#define  RIGHT_ARM_STRUCT    2
#define  BODY_STRUCT        15


#define LABEL_LEFT_ARM  1
#define LABEL_RIGHT_ARM 2